### ISSUE TITLE
Add an option to Sort Tabs automatically

### ISSUE THREAD

**Issue by akai1831** [f-jiang/sort-those-tabs#1]
Hi,

Could you an option to sort the tabs when Chrome starts, sort by Tab Title or Name

Thanks!

**Comment by f-jiang** [comment]
Sounds like a good idea. I'll consider adding your feature in the near future.

Thanks

**Comment by f-jiang** [comment]
After a second thought, an auto-sort feature on browser startup is beyond the scope of this extension's intended purpose, which is to provide an easier way for the user to manually sort the tabs in a browsing session. What I can add is a "sort by tab title/name" button that the user would click for a browser window's tabs to be sorted.

**Comment by akai1831** [comment]
Would that be possible to add an option for auto sorting within an interval time without clicking or pressing any key, this would be handy to our company dashboard without any user intervention. Thanks

**Comment by f-jiang** [comment]
Unfortunately this extension isn't designed for automatic sorting that doesn't require user intervention. The most that I can implement is the auto-sort button that I mentioned earlier.

**Comment by akai1831** [comment]
Alright! Thanks

**Comment by akai1831** [comment]
Bringing this issue again. Here's one sample of Plugin which will sort the tab automatically within an interval time via options page, but it lacks to auto sort the tab by title. As we have set of tabs loaded automatically when browser starts, it would be great if you could add an options to sort the tabs by title without any User intervention or much better idea.

https://github.com/100/Tab-Organizer

**Comment by f-jiang** [comment]
Updated release with requested changes can be found on the [Chrome Web Store](https://chrome.google.com/webstore/detail/sort-those-tabs/hkpcnabklhpajnjmmfmnpihcjjkojjpg).

**Comment by akai1831** [comment]
@f-jiang this can be annoying for you but I couldn't see any way to set the tabs to sort automatically. I can only sort the tabs by title or domain and Apply or Reset the changes. Please enlighten me. Thanks

**Comment by f-jiang** [comment]
This extension is not meant for sorting without user interaction. If you want that feature you'll have to find another extension.
